# Per-persona git configuration, generated at *activation* time.
#
# The persona list lives in a TOML file outside the flake and is never read
# during evaluation, so the flake stays pure: no `--impure`, and a missing file
# is not an error (git ignores an include path that does not exist).
#
# For every persona the module can
#
#   * pull in a hand-maintained gitconfig for repositories under its directory,
#   * make a stored credential reachable *only* from that directory, and
#   * drop a direnv `.envrc` at the root of that directory.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.gitPersonas;

  personasInclude = pkgs.writeShellApplication {
    name = "git-personas-include";
    runtimeInputs = [
      pkgs.jq
      pkgs.yq-go
    ];
    text = ''
      usage="usage: git-personas-include <personas.toml> <out.gitconfig> <repos-root> <config-dir>"
      personas="''${1:?$usage}"
      out="''${2:?$usage}"
      root="''${3:?$usage}"
      cfgdir="''${4:?$usage}"

      mkdir -p "$(dirname "$out")"
      tmp="$(mktemp "$out.XXXXXX")"
      trap 'rm -f "$tmp"' EXIT

      {
        echo "# Generated from $personas by home-manager activation. Do not edit."
        if [ -r "$personas" ]; then
          yq -p toml -o json "$personas" | jq -r --arg root "$root" --arg cfgdir "$cfgdir" '
            (.gitPersonas // []) as $personas
            | ([$personas[] | (.credentialHosts // [])[]] | unique) as $hosts
            | (
                # An empty helper resets the list inherited from the system and
                # user config, so the credential for these hosts is unreachable
                # until one of the includeIf blocks below puts a helper back.
                # Emitted first: git applies credential settings in file order.
                $hosts[]
                | "[credential \"\(.)\"]\n\thelper ="
              ),
              (
                $personas[]
                | "[includeIf \"gitdir:\($root)/\(.dir)/\"]\n\tpath = \($cfgdir)/\(.configFile)"
              )
          '
        fi
      } >"$tmp"

      mv "$tmp" "$out"
    '';
  };

  personasEnvrc = pkgs.writeShellApplication {
    name = "git-personas-envrc";
    runtimeInputs = [
      pkgs.jq
      pkgs.yq-go
      pkgs.coreutils
    ];
    text = ''
      usage="usage: git-personas-envrc <personas.toml> <repos-root>"
      personas="''${1:?$usage}"
      root="''${2:?$usage}"
      marker="# Generated by git-personas.nix at home-manager activation. Do not edit."

      [ -r "$personas" ] || exit 0

      # The body is carried base64-encoded so newlines survive the TSV.
      while IFS=$'\t' read -r dir body; do
        if [ -z "$dir" ] || [ -z "$body" ]; then
          continue
        fi

        envrc="$root/$dir/.envrc"

        # Never clobber an .envrc this script did not write.
        if [ -e "$envrc" ] && ! head -n 1 "$envrc" | grep -qF "$marker"; then
          echo "git-personas-envrc: leaving $envrc alone (not generated here)" >&2
          continue
        fi

        mkdir -p "$(dirname "$envrc")"
        {
          echo "$marker"
          printf '%s' "$body" | base64 -d
          echo
        } >"$envrc"
      done < <(yq -p toml -o json "$personas" | jq -r '
        (.gitPersonas // [])[]
        | select(.env)
        | [.dir, ((.env | to_entries | map("export \(.key)=\"\(.value)\"") | join("\n")) | @base64)]
        | @tsv
      ')
    '';
  };
in
{
  options.programs.gitPersonas = {
    enable = lib.mkEnableOption "per-persona git configuration generated at activation time";

    personasFile = lib.mkOption {
      type = lib.types.str;
      example = "/home/alice/dotfiles/personas.toml";
      description = ''
        Absolute path to the TOML file describing the personas. Read at
        activation time only, so it may live outside the flake and may be
        absent.

        ```toml
        [[gitPersonas]]
        dir = "github.com/example-org"
        configFile = "example-org"
        credentialHosts = ["https://git.example.com"]
        env.GITLAB_HOST = "git.example.com"
        ```

        `dir` is resolved against [](#opt-programs.gitPersonas.reposRoot) and
        `configFile` against [](#opt-programs.gitPersonas.configDir);
        `credentialHosts` and `env` are optional.
      '';
    };

    reposRoot = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/repos";
      defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/repos"'';
      description = "Directory the per-persona `dir` entries are resolved against, typically a ghq root.";
    };

    configDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.config/git.custom";
      defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/.config/git.custom"'';
      description = ''
        Directory holding the hand-maintained per-persona gitconfig files. The
        generated include is written here as well.
      '';
    };

    includeFile = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.configDir}/personas.gitconfig";
      defaultText = lib.literalExpression ''"''${config.programs.gitPersonas.configDir}/personas.gitconfig"'';
      description = "Path of the generated include, added to {option}`programs.git.includes`.";
    };

    writeEnvrc = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether to write a direnv `.envrc` exporting each persona's `env` at the
        root of its directory. An existing `.envrc` that this module did not
        write is left untouched.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Last in the include chain, so a persona's own settings win.
    programs.git.includes = lib.mkAfter [ { path = cfg.includeFile; } ];

    home.activation.gitPersonasInclude = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      run ${personasInclude}/bin/git-personas-include \
        ${lib.escapeShellArg cfg.personasFile} \
        ${lib.escapeShellArg cfg.includeFile} \
        ${lib.escapeShellArg cfg.reposRoot} \
        ${lib.escapeShellArg cfg.configDir}
    '';

    home.activation.gitPersonasEnvrc = lib.mkIf cfg.writeEnvrc (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        run ${personasEnvrc}/bin/git-personas-envrc \
          ${lib.escapeShellArg cfg.personasFile} \
          ${lib.escapeShellArg cfg.reposRoot}
      ''
    );
  };
}
