# Per-client git configuration, generated at *activation* time.
#
# The client list lives in a JSON file outside the flake and is never read
# during evaluation, so the flake stays pure: no `--impure`, and a missing file
# is not an error (git ignores an include path that does not exist).
#
# For every client the module can
#
#   * pull in a hand-maintained gitconfig for repositories under its directory,
#   * make a stored credential reachable *only* from that directory, and
#   * drop a direnv `.envrc` at the root of that directory.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.programs.gitClients;

  clientsInclude = pkgs.writeShellApplication {
    name = "git-clients-include";
    runtimeInputs = [ pkgs.jq ];
    text = ''
      usage="usage: git-clients-include <clients.json> <out.gitconfig> <repos-root> <config-dir>"
      clients="''${1:?$usage}"
      out="''${2:?$usage}"
      root="''${3:?$usage}"
      cfgdir="''${4:?$usage}"

      mkdir -p "$(dirname "$out")"
      tmp="$(mktemp "$out.XXXXXX")"
      trap 'rm -f "$tmp"' EXIT

      {
        echo "# Generated from $clients by home-manager activation. Do not edit."
        if [ -r "$clients" ]; then
          jq -r --arg root "$root" --arg cfgdir "$cfgdir" '
            (.gitClients // []) as $clients
            | ([$clients[] | (.credentialHosts // [])[]] | unique) as $hosts
            | (
                # An empty helper resets the list inherited from the system and
                # user config, so the credential for these hosts is unreachable
                # until one of the includeIf blocks below puts a helper back.
                # Emitted first: git applies credential settings in file order.
                $hosts[]
                | "[credential \"\(.)\"]\n\thelper ="
              ),
              (
                $clients[]
                | "[includeIf \"gitdir:\($root)/\(.dir)/\"]\n\tpath = \($cfgdir)/\(.configFile)"
              )
          ' "$clients"
        fi
      } >"$tmp"

      mv "$tmp" "$out"
    '';
  };

  clientsEnvrc = pkgs.writeShellApplication {
    name = "git-clients-envrc";
    runtimeInputs = [
      pkgs.jq
      pkgs.coreutils
    ];
    text = ''
      usage="usage: git-clients-envrc <clients.json> <repos-root>"
      clients="''${1:?$usage}"
      root="''${2:?$usage}"
      marker="# Generated by git-clients.nix at home-manager activation. Do not edit."

      [ -r "$clients" ] || exit 0

      # The body is carried base64-encoded so newlines survive the TSV.
      while IFS=$'\t' read -r dir body; do
        if [ -z "$dir" ] || [ -z "$body" ]; then
          continue
        fi

        envrc="$root/$dir/.envrc"

        # Never clobber an .envrc this script did not write.
        if [ -e "$envrc" ] && ! head -n 1 "$envrc" | grep -qF "$marker"; then
          echo "git-clients-envrc: leaving $envrc alone (not generated here)" >&2
          continue
        fi

        mkdir -p "$(dirname "$envrc")"
        {
          echo "$marker"
          printf '%s' "$body" | base64 -d
          echo
        } >"$envrc"
      done < <(jq -r '
        (.gitClients // [])[]
        | select(.env)
        | [.dir, ((.env | to_entries | map("export \(.key)=\"\(.value)\"") | join("\n")) | @base64)]
        | @tsv
      ' "$clients")
    '';
  };
in
{
  options.programs.gitClients = {
    enable = lib.mkEnableOption "per-client git configuration generated at activation time";

    clientsFile = lib.mkOption {
      type = lib.types.str;
      example = "/home/alice/dotfiles/secrets.json";
      description = ''
        Absolute path to the JSON file describing the clients. Read at
        activation time only, so it may live outside the flake and may be
        absent.

        ```json
        {
          "gitClients": [
            {
              "dir": "github.com/example-org",
              "configFile": "example-org",
              "credentialHosts": ["https://git.example.com"],
              "env": { "GITLAB_HOST": "git.example.com" }
            }
          ]
        }
        ```

        `dir` is resolved against [](#opt-programs.gitClients.reposRoot) and
        `configFile` against [](#opt-programs.gitClients.configDir);
        `credentialHosts` and `env` are optional.
      '';
    };

    reposRoot = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/repos";
      defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/repos"'';
      description = "Directory the per-client `dir` entries are resolved against, typically a ghq root.";
    };

    configDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.home.homeDirectory}/.config/git.custom";
      defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/.config/git.custom"'';
      description = ''
        Directory holding the hand-maintained per-client gitconfig files. The
        generated include is written here as well.
      '';
    };

    includeFile = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.configDir}/clients.gitconfig";
      defaultText = lib.literalExpression ''"''${config.programs.gitClients.configDir}/clients.gitconfig"'';
      description = "Path of the generated include, added to {option}`programs.git.includes`.";
    };

    writeEnvrc = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether to write a direnv `.envrc` exporting each client's `env` at the
        root of its directory. An existing `.envrc` that this module did not
        write is left untouched.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Last in the include chain, so a client's own settings win.
    programs.git.includes = lib.mkAfter [ { path = cfg.includeFile; } ];

    home.activation.gitClientsInclude = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      run ${clientsInclude}/bin/git-clients-include \
        ${lib.escapeShellArg cfg.clientsFile} \
        ${lib.escapeShellArg cfg.includeFile} \
        ${lib.escapeShellArg cfg.reposRoot} \
        ${lib.escapeShellArg cfg.configDir}
    '';

    home.activation.gitClientsEnvrc = lib.mkIf cfg.writeEnvrc (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        run ${clientsEnvrc}/bin/git-clients-envrc \
          ${lib.escapeShellArg cfg.clientsFile} \
          ${lib.escapeShellArg cfg.reposRoot}
      ''
    );
  };
}
